CMAKE_MINIMUM_REQUIRED(VERSION 3.10)
PROJECT(DCAP)

# Set device
IF (${TARGET_PLATFORM} MATCHES "imx8mini")
    SET(DEVICE VS800)
ELSEIF (${TARGET_PLATFORM} MATCHES "imx8plus")
    SET(DEVICE VS1000Pro)
ELSE ()
    MESSAGE(FATAL_ERROR "Unsupported platform: " ${TARGET_PLATFORM})
ENDIF ()

SET(DCAP_INC ${CMAKE_CURRENT_SOURCE_DIR}/inc)
SET(DRIVER_INC ${CMAKE_CURRENT_SOURCE_DIR}/drivers/${DEVICE})
FILE(GLOB DCAP_SRC ${CMAKE_CURRENT_SOURCE_DIR}/src/*.c*)
FILE(GLOB DRIVER_SRC ${CMAKE_CURRENT_SOURCE_DIR}/drivers/${DEVICE}/*.c*)


ADD_LIBRARY(${PROJECT_NAME} STATIC
        ${DCAP_SRC}
        ${DRIVER_SRC}
        )

TARGET_INCLUDE_DIRECTORIES(${PROJECT_NAME} PUBLIC
        ${DCAP_INC}
        ${DRIVER_INC}
        )

TARGET_LINK_LIBRARIES(${PROJECT_NAME} PUBLIC
        ${OpenCV_LIBS}
        )
